apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: neobank-spring-boot-service
  title: NeoBank Spring Boot Microservice
  description: Create a new Spring Boot microservice for the NeoBank platform with CI/CD, Docker, and Backstage integration pre-configured.
  tags:
    - java
    - spring-boot
    - neobank
    - recommended
spec:
  owner: team-neobank
  type: service

  parameters:
    - title: Service Information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Service Name
          type: string
          description: Unique name for your microservice (e.g., payment-service)
          pattern: '^[a-z0-9][a-z0-9-]+[a-z0-9]$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: What does this service do?
        owner:
          title: Owner Team
          type: string
          description: Team that owns this service
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
        port:
          title: Server Port
          type: integer
          default: 8081
          description: The port this service will run on

    - title: Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          port: ${{ parameters.port }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: private

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Open Repository
        url: ${{ steps['publish'].output.remoteUrl }}
        icon: github
      - title: View in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}