apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: neobank-rest-api
  title: NeoBank REST API
  description: Complete REST API for the NeoBank banking platform including authentication, accounts, transactions, cards, and loans.
  tags:
    - rest
    - banking
    - openapi
  links:
    - url: http://localhost:8080/swagger-ui.html
      title: Swagger UI
      icon: web
spec:
  type: openapi
  lifecycle: production
  owner: team-neobank
  system: neobank-platform
  definition: |
    openapi: 3.0.3
    info:
      title: NeoBank API
      version: "1.0"
      description: Modern Banking Platform API
    servers:
      - url: http://localhost:8080
        description: Local development
    security:
      - bearer-jwt: []
    paths:
      /api/auth/register:
        post:
          tags: [Authentication]
          summary: Register a new user
          security: []
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RegisterRequest'
          responses:
            '200':
              description: User registered successfully
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/AuthResponse'
      /api/auth/login:
        post:
          tags: [Authentication]
          summary: Login with email and password
          security: []
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/LoginRequest'
          responses:
            '200':
              description: Login successful
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/AuthResponse'
      /api/accounts:
        get:
          tags: [Accounts]
          summary: Get current user's accounts
          responses:
            '200':
              description: List of accounts
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/AccountResponse'
        post:
          tags: [Accounts]
          summary: Create a new account
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CreateAccountRequest'
          responses:
            '200':
              description: Account created
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/AccountResponse'
      /api/accounts/{id}/freeze:
        post:
          tags: [Accounts]
          summary: Freeze an account
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: integer
          responses:
            '204':
              description: Account frozen
      /api/transactions/transfer:
        post:
          tags: [Transactions]
          summary: Transfer money between accounts
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/TransferRequest'
          responses:
            '200':
              description: Transfer completed
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/TransactionResponse'
      /api/transactions/account/{accountId}:
        get:
          tags: [Transactions]
          summary: Get transactions for an account
          parameters:
            - name: accountId
              in: path
              required: true
              schema:
                type: integer
          responses:
            '200':
              description: List of transactions
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/TransactionResponse'
      /api/cards:
        get:
          tags: [Cards]
          summary: Get current user's cards
          responses:
            '200':
              description: List of cards
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/CardResponse'
        post:
          tags: [Cards]
          summary: Create a new card
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CreateCardRequest'
          responses:
            '200':
              description: Card created
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/CardResponse'
      /api/loans/apply:
        post:
          tags: [Loans]
          summary: Apply for a loan
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/LoanApplicationRequest'
          responses:
            '200':
              description: Loan application submitted
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/LoanResponse'
      /api/loans:
        get:
          tags: [Loans]
          summary: Get current user's loans
          responses:
            '200':
              description: List of loans
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/LoanResponse'
    components:
      securitySchemes:
        bearer-jwt:
          type: http
          scheme: bearer
          bearerFormat: JWT
      schemas:
        RegisterRequest:
          type: object
          required: [email, password, firstName, lastName]
          properties:
            email:
              type: string
              format: email
            password:
              type: string
              minLength: 8
            firstName:
              type: string
            lastName:
              type: string
            phoneNumber:
              type: string
        LoginRequest:
          type: object
          required: [email, password]
          properties:
            email:
              type: string
              format: email
            password:
              type: string
        AuthResponse:
          type: object
          properties:
            token:
              type: string
            email:
              type: string
            firstName:
              type: string
            lastName:
              type: string
        AccountResponse:
          type: object
          properties:
            id:
              type: integer
            accountNumber:
              type: string
            balance:
              type: number
            type:
              type: string
              enum: [CHECKING, SAVINGS, INVESTMENT]
            status:
              type: string
              enum: [ACTIVE, FROZEN, CLOSED]
            createdAt:
              type: string
              format: date-time
        CreateAccountRequest:
          type: object
          required: [type]
          properties:
            type:
              type: string
              enum: [CHECKING, SAVINGS, INVESTMENT]
        TransferRequest:
          type: object
          required: [sourceAccountNumber, destinationAccountNumber, amount]
          properties:
            sourceAccountNumber:
              type: string
            destinationAccountNumber:
              type: string
            amount:
              type: number
            description:
              type: string
        TransactionResponse:
          type: object
          properties:
            id:
              type: integer
            transactionId:
              type: string
            sourceAccountNumber:
              type: string
            destinationAccountNumber:
              type: string
            amount:
              type: number
            type:
              type: string
              enum: [DEPOSIT, WITHDRAWAL, TRANSFER, PAYMENT]
            status:
              type: string
              enum: [PENDING, COMPLETED, FAILED, CANCELLED]
            description:
              type: string
            createdAt:
              type: string
              format: date-time
            completedAt:
              type: string
              format: date-time
        CreateCardRequest:
          type: object
          required: [type, accountNumber]
          properties:
            type:
              type: string
              enum: [DEBIT, CREDIT]
            accountNumber:
              type: string
            creditLimit:
              type: number
        CardResponse:
          type: object
          properties:
            id:
              type: integer
            cardNumber:
              type: string
            maskedCardNumber:
              type: string
            expiryDate:
              type: string
              format: date
            type:
              type: string
              enum: [DEBIT, CREDIT]
            status:
              type: string
              enum: [ACTIVE, BLOCKED, EXPIRED, CANCELLED]
            accountNumber:
              type: string
            creditLimit:
              type: number
            availableCredit:
              type: number
        LoanApplicationRequest:
          type: object
          required: [type, principalAmount, termMonths]
          properties:
            type:
              type: string
              enum: [PERSONAL, MORTGAGE, AUTO, STUDENT]
            principalAmount:
              type: number
            termMonths:
              type: integer
        LoanResponse:
          type: object
          properties:
            id:
              type: integer
            loanNumber:
              type: string
            principalAmount:
              type: number
            interestRate:
              type: number
            termMonths:
              type: integer
            monthlyPayment:
              type: number
            remainingBalance:
              type: number
            type:
              type: string
              enum: [PERSONAL, MORTGAGE, AUTO, STUDENT]
            status:
              type: string
              enum: [PENDING, APPROVED, REJECTED, ACTIVE, PAID_OFF, DEFAULTED]
            createdAt:
              type: string
              format: date-time
            approvedAt:
              type: string
              format: date-time