apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: neobank-platform
  title: NeoBank Platform
  description: Complete digital banking platform providing retail banking services including accounts, transactions, cards, and loans.
  tags:
    - banking
    - fintech
spec:
  owner: team-neobank

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: neobank-postgresql
  title: NeoBank PostgreSQL Database
  description: Primary PostgreSQL database for NeoBank - stores users, accounts, transactions, cards, and loans.
  tags:
    - postgresql
    - database
spec:
  type: database
  owner: team-neobank
  system: neobank-platform

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-neobank
  title: NeoBank Engineering Team
  description: Core engineering team responsible for the NeoBank platform.
spec:
  type: team
  profile:
    displayName: NeoBank Team
    email: engineering@neobank.com
  children: []
  members:
    - Solano204